SilverStripe\View\SSViewer:
  source_file_comments: true
  themes:
    - '$public'
    - 'simple'
    - '$default'

DNADesign\Elemental\Models\BaseElement:
  default_global_elements: true

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'colymba/gridfield-bulk-editing-tools:client/dist/js/main.js'
    - 'colymba/gridfield-bulk-editing-tools:client/lang/en.js'
  extra_requirements_css:
    - 'colymba/gridfield-bulk-editing-tools:client/dist/styles/main.css'

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'site/client/css/editor.css'